source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'SNLWeekChartView' do
  pod "SNLWeekChartView", :path => "../"
  
end

target 'Tests' do
  pod "SNLWeekChartView", :path => "../"

end
