source 'https://github.com/CocoaPods/Specs.git'

target 'SNLWeekChartView', :exclusive => true do
  pod "SNLWeekChartView", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "SNLWeekChartView", :path => "../"

  
end
